services:
  # Frontend-Only Service (React app)
  frontend:
    image: fluxstack-frontend:latest
    ports:
      - "8080:80"  # Acesso direto ao frontend
    environment:
      - API_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - fluxstack-network
    restart: unless-stopped

  # Backend-Only Service (API)
  backend:
    image: fluxstack-backend:latest
    ports:
      - "3001:3001"  # Acesso direto à API
    environment:
      - NODE_ENV=production
      - BACKEND_PORT=3001
      - DATABASE_URL=postgresql://fluxstack:password@postgres:5432/fluxstack
      - CORS_ORIGINS=http://localhost:8080,http://192.168.1.22:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fluxstack-network
    restart: unless-stopped

  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fluxstack
      - POSTGRES_USER=fluxstack
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Acesso direto ao DB para debug
    networks:
      - fluxstack-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fluxstack -d fluxstack"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  fluxstack-network:
    driver: bridge